### ISSUE TITLE
Outdated Wireshark Lua API links

### ISSUE THREAD

**Issue by thirtythreeforty** [mika-s/mika-s.github.io#1]
Hello! Awesome tutorial on Wireshark dissectors.  Thank you very much.

You might be interested to know that all your links to the Wireshark docs are unfortunately obsolete, since they monkeyed with their docs. Links like [the one to `Tvb`](https://wiki.wireshark.org/LuaAPI/Tvb#Tvb). Not the end of the world, but it might be nice for an update to point to the new links.

**Comment by mika-s** [comment]
Thanks for telling me, @thirtythreeforty.

I've updated the links.
