### ISSUE TITLE
something wrong when I put mongodb.lua into plugins/ sub-directory

### ISSUE THREAD

**Issue by shelvsky** [mika-s/mika-s.github.io#3]
An Error comes out if I put demos into plugins/ sub-directory when I use your demo to work with Wireshark 3.2.x: 
**bad argument #2 to 'Proto' (Proto_new: there cannot be two protocols with the same description)**
I searched on google and do not have a clue with it, any idea on this one? thx

**Comment by mika-s** [comment]
From what I can tell, you have two or more dissectors in the plugins directory with the same description. They probably have the same name as well. You have to make sure all the dissectors have unique names and descriptions compared to all other dissectors. If you have multiple versions of mongodb.lua, then you have to edit each of them so they get unique values. Or you could delete/move unneeded versions.

The description is this thing:

mongodb_protocol = Proto("MongoDB",  **"MongoDB Protocol"**)

and the name is the first argument.

**Comment by shelvsky** [comment]
it has been fixed. It turns out that your demos can't be in the plugins/ sub-directory, instead if I put them in the Wireshark root directory, everything's fine. But still, I can't figure it out why it is.
